# Change these first
owner: AutiCodes # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: AutiCodes.nl
    url: https://auticodes.nl
  - name: AllDayTechAndGaming blog
    url: https://alldaytechandgaming.nl
  - name: T.R.M.C Wordpress
    url: https://trmc.nl
  - name: T.R.M.C Club Manager
    url: https://club.trmc.nl
  - name: Domain Name Server
    check: "tcp-ping"
    url: 78.47.239.19
    port: 53
  - name: Email inbound
    check: "tcp-ping"
    url: 78.47.239.19
    port: 993
  - name: Email outbound
    check: "tcp-ping"
    url: 78.47.239.19
    port: 465

status-website:
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://avatars.githubusercontent.com/u/31496522?v=4&size=64
  favicon: https://avatars.githubusercontent.com/u/31496522?v=4&
  name: Uptime
  introTitle: "The main web services uptime page for AutiCodes"
  introMessage: t.b.c
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Auticodes.nl
      href: https://auticodes.nl    
  theme: night

